AUTOCARIS_URL = "https://www.autocaris.cz"
AUTOCARIS_DEALERS_URL = "/downloadcontent/subjects.php"
AUTOCARIS_ADS_URL = "/downloadcontent/cars.php"

AUTOCARIS_LOGIN_NAME_PARAM = "?name="
AUTOCARIS_LOGIN_PW_PARAM = "&password="

AUTOCARIS_LOGIN_NAME = "kratochvil"
AUTOCARIS_LOGIN_PW = "krat_299"

AUTOCARIS_DEALERS_URL_FINAL = AUTOCARIS_URL + AUTOCARIS_DEALERS_URL
AUTOCARIS_ADS_URL_FINAL = AUTOCARIS_URL + AUTOCARIS_ADS_URL
